apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: axis-zero
data:
  config.yaml: |
   
    tunnel: ff90f9fa-bf7b-4326-bf5a-47f92670b80e  # Replace with your tunnel ID
   
    credentials-file: /etc/cloudflared/credentials/credentials.json
    
    metrics: 0.0.0.0:20241
    metrics-update-freq: 5s
    protocol: http2
    loglevel: info

    ingress:
      - hostname: axiszero.ca  # Replace with your domain
        service: http://axis-zero-service:80
      - hostname: www.axiszero.ca  # Replace with your domain
        service: http://axis-zero-service:80
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  namespace: axis-zero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        volumeMounts:
        - name: cloudflared-config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: credentials
          mountPath: /etc/cloudflared/credentials
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 20241
          name: metrics
      volumes:
      - name: cloudflared-config
        configMap:
          name: cloudflared-config
      - name: credentials
        secret:
          secretName: cloudflare-axis-zero-tunnel-credentials

---

# Service for metrics
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics-service
  namespace: axis-zero
  labels:
    app: cloudflared-tunnel
    monitoring: "enabled"
spec:
  ports:
  - port: 20241
    targetPort: 20241
    protocol: TCP
    name: metrics
  selector:
    app: cloudflared-tunnel
#  clusterIP: None
