NAMESPACES=(
    "cloud"
    "metallb-system"
    "nfs"
    "streaming"
)

TLS_SECRETS=(
    "cloud"
    "streaming"
    "network"
)

TLS_NAME="local-tls"
WORKING_DIR="./"
CERTS_DIR="./certs"
BACKUP_DIR="./certs/backup"