NAMESPACES=(
    "cloud"
    "metallb-system"
    "nfs"
    "streaming"
)

TLS_SECRETS=(
    "cloud"
    "streaming"
    "network"
    "gitea"
    "homarr"
    "monitoring"
)

TLS_NAME="local-tls"
WORKING_DIR="./"
CERTS_DIR="./certs"
BACKUP_DIR="./backup"