[req]
default_bits = 2048
default_md = sha256
prompt = no
distinguished_name = req_local_env
req_extensions = v3_req
x509_extensions = v3_req

[req_local_env]
C = CN
ST = Saskatoon
L = SK
O = Local env
OU = IT Local
CN = HomeLab CA

[v3_req]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = home.net
DNS.2 = *.home.net
IP.1 = <zima proxmox ip>    # Zima proxmox
IP.2 = <dell proxmox ip>    # Dell proxmox