---
# PVC shared accross streaming apps.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: streaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi