---
# PVC shared accross streaming apps.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: streaming
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi