apiVersion: v1
kind: Service
metadata: 
  name: net-external-ip-service
  namespace: proxy
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
---

apiVersion: v1
kind: Endpoints
metadata:
  name: net-external-ip-service
  namespace: proxy
subsets:
  - addresses:
      - ip: 192.168.8.1
    ports: 
      - port: 80
        protocol: TCP
