apiVersion: v1
kind: Service
metadata: 
  name: net-external-ip-service
  namespace: reverse_proxy
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
---

apiVersion: v1
kind: EndPoints
metadata:
  name: net-external-ip-service
  namespace: reverse_proxy
subsets:
  - addresses:
      - ip: 192.168.8.1
    ports: 
      - port: 80
        protocol: TCP