# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name:  gitea-data
#   namespace: gitea
# spec:
#   storageClassName: nfs-client
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  gitea-data-pvc
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi