apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: gitea
data:
  postgresql.conf: |
    ssl = on
    ssl_cert_file = '/certs/tls.crt'
    ssl_key_file = '/certs/tls.key'
    listen_addresses = '*'