---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: runner-secret
  namespace: gitea
spec:
  encryptedData:
    token: AgAZ+B8yqg3kQPGd4Rk0PIHA5peCrSigSx4VQviqez0k6oQ+vweKUijpxrElDnh+JKh/aqF7vv5StNf27+/6zc289BugT0NV86jxAAfQah5LIaP2cNqrxqpDHkFBwCHFnp1RxwT3hfyC8ksUPfC25RnSaFrB/Y3YP7q6fAn890rIwnDAPRRscN6SZnpTR1WyFXAidbbO01U/qbKSxtQp/hrP7NpUtb1TVhKWHSOxtT6NXBgKiWY3VOAuAzPOdJug7ZHeQyh2ECS7BOgyRHHUkI8A2OX0vwaj4wA1fBpUjFTecmbuKFuif3sIjhPHP1LePuvwl2lP+sZJ2jdF9fhNHR6luPO+5Jzrup44X+a10NxsFdbVJrsQ4oJXaVXrXID6lmRf22UNcJYc8io11Ahigunx+dhocwJQWJCzjyEqGX5jYdd8v7BQ/xBZlZH29Kz1hPGgNtTdyxDnRVQeUBGrfwBqkVadeS5REsY9v/CF5P6eOHFHkl0ySlqx8HWP8uLLSp3vmPc7++M/HKlfQgNfi4HCAAXdsoMllT0tktA5UYRS0UsxMvOC84KnpIMAypdjQfvsJ++Gc7fxUkHrORYR4JqAGXhr1pqFWb4rhVfkpZTd8SuPiq+tlVILmdoAcXZRa7rDdRyN7qSiJxH3XhAeDOaKEa0HJVBz5YqnvH5vvSvv6hsFFdgfcYrxMX8rTlIktqqy68mZc3To/gUn30jDq2t+DcNwAPVClaZUionYfYPy5WJyQpPzTxRZ
  template:
    metadata:
      name: runner-secret
      namespace: gitea
    type: Opaque
