apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: cloud
type: Opaque
stringData:
  nextcloud-admin-user: admin
  nextcloud-admin-password: ${NEXTCLOUD_ADMIN_PASSWORD}
  nextcloud-db-name: nextcloud
  nextcloud-db-user: nextcloud_user
  nextcloud-db-password: ${MARIADB_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: cloud
type: Opaque
stringData:
  mariadb-database: nextcloud
  mariadb-user: nextcloud_user
  mariadb-password: ${MARIADB_PASSWORD}
  mariadb-root-password: ${MARIADB_ROOT_PASSWORD}