#
# NextCloud Collabora
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      containers:
      - name: collabora
        image: collabora/code:latest 
        ports:
        - containerPort: 9980
        env:
        - name: aliasgroup1
          value: "nextcloud.home.net"
        - name: name_server
          value: 'https://collabora.home.net'
        - name: NC_DOMAIN
          value: 'https://collabora.home.net'
        - name: dictionaries
          value: "en pt_BR fr" # Optional: Limit language support to improve performance [citation:1][citation:7]
        - name: extra_params
          value: "--o:ssl.enable=false --o:ssl.termination=true --o:server_name=collabora.home.net"
        - name: DONT_GEN_SSL_CERT
          value: "YES"  
        securityContext:
          capabilities:
            add: ["MKNOD"] # Required by Collabora [citation:1][citation:7]
      volumes:
      - name: collabora-config
        configMap:
          name: collabora-config
      - name: coolwsd-base-dir
        emptyDir: {}
---
#
# Collabora service
#
apiVersion: v1
kind: Service
metadata:
  name: collabora
  namespace: cloud
spec:
  type: LoadBalancer
  selector:
    app: collabora
  ports:
    - protocol: TCP
      port: 9980
      targetPort: 9980
