#radarr.yml

# Enabling "quality_definition" will cause trouble finding releases for Optimized 4K/1080p  
# since the minimum quality values from Trash Guides are too high

#quality_definition:
#  type: movie

delete_old_custom_formats: false
replace_existing_custom_formats: false

quality_profiles:
  - name: Maximum 4K/HDR
    reset_unmatched_scores:
      enabled: true
    upgrade:
      allowed: yes
      until_quality: Remux-2160p
      until_score: 10000
    min_format_score: 4800
    score_set: sqp-2-2160p
    qualities:
      - name: Remux-2160p
      - name: Bluray-2160p
      - name: Web 2160p
        qualities:
          - WEBRip-2160p
          - WEBDL-2160p

  - name: Maximum 4K/SDR
    reset_unmatched_scores:
      enabled: true
    upgrade:
      allowed: yes
      until_quality: Remux-2160p
      until_score: 10000
    min_format_score: 3000
    score_set: sqp-2-2160p
    qualities:
      - name: Remux-2160p
      - name: Bluray-2160p
      - name: Web 2160p
        qualities:
          - WEBRip-2160p
          - WEBDL-2160p

  - name: Maximum 1080p
    reset_unmatched_scores:
      enabled: true
    upgrade:
      allowed: yes
      until_quality: Remux-1080p
      until_score: 10000
    min_format_score: 3000
    score_set: sqp-2-1080p
    qualities:
      - name: Remux-1080p
        enabled: true
      - name: Bluray-1080p
        enabled: true
      - name: Web 1080p
        enabled: true
        qualities:
          - WEBRip-1080p
          - WEBDL-1080p

  - name: Optimized 4k
    reset_unmatched_scores:
      enabled: true
    upgrade:
      allowed: true
      until_quality: Web 2160p
      until_score: 10000
    min_format_score: 1500
    score_set: sqp-1-2160p
    qualities:
      - name: Web 2160p
        qualities:
          - WEBRip-2160p
          - WEBDL-2160p
      - name: Bluray-2160p
      - name: Remux-2160p
        enabled: false

  - name: Optimized 1080p
    reset_unmatched_scores:
      enabled: true
    upgrade:
      allowed: yes
      until_quality: Web 1080p
      until_score: 10000
    min_format_score: 1500
    score_set: sqp-1-1080p
    qualities:
      - name: Remux-1080p
        enabled: false
      - name: Bluray-1080p
        enabled: true
      - name: HDTV-1080p
        enabled: true
      - name: Web 1080p
        enabled: true
        qualities:
          - WEBRip-1080p
          - WEBDL-1080p
  
custom_formats:

  - trash_ids:
      - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
    assign_scores_to:
      - name: Optimized 1080p
        score: 700

  - trash_ids:
      - fb392fb0d61a010ae38e49ceaa24a1ef # 2160p      
      - b2be17d608fc88818940cd1833b0b24c # 720p
    assign_scores_to:
      - name: Maximum 1080p
        score: -10000
      - name: Optimized 1080p
        score: -10000

  # Movie Versions
  - trash_ids:
      - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
      - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
      - 0f12c086e289cf966fa5948eac571f44 # Hybrid
      - eecf3a857724171f968a66cb5719e152 # IMAX
      - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
      - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
      - 09d9dd29a0fc958f9796e65c2a8864b4 # Open Matte
      - 570bc9ebecd92723d2d21500f4be314c # Remaster
      - 957d0f44b592285f26449575e8b1167e # Special Edition
      - e9001909a4c88013a359d0b9920d7bea # Theatrical Cut
      - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome         
    assign_scores_to:
      - name: Maximum 4K/HDR
      - name: Maximum 4K/SDR
      - name: Maximum 1080p
      - name: Optimized 4k
      - name: Optimized 1080p

  - trash_ids:
      - 9170d55c319f4fe40da8711ba9d8050d # x265
    assign_scores_to:
      - name: Optimized 4k

  # Audio

  - trash_ids:
      - 240770601cc226190c367ef59aba7463 # AAC
    assign_scores_to:
      - name: Optimized 1080p
        score: 2400

  - trash_ids:
      - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 5000
      - name: Maximum 4K/SDR
        score: 5000
      - name: Maximum 1080p
        score: 5000
      - name: Optimized 4k
        score: -10000
      - name: Optimized 1080p
        score: -10000

  - trash_ids:
      - 3cafb66171b47f226146a0770576870f # TrueHD
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 4000
      - name: Maximum 4K/SDR
        score: 4000
      - name: Maximum 1080p
        score: 4000
      - name: Optimized 4k
        score: -10000
      - name: Optimized 1080p
        score: -10000

  - trash_ids:
      - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 3900
      - name: Maximum 4K/SDR
        score: 3900
      - name: Maximum 1080p
        score: 3900
      - name: Optimized 4k
        score: -10000
      - name: Optimized 1080p
        score: -10000

  - trash_ids:
      - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 3700
      - name: Maximum 4K/SDR
        score: 3700        
      - name: Maximum 1080p
        score: 3700
      - name: Optimized 4k
        score: 2000

  - trash_ids:
      - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 3500
      - name: Maximum 4K/SDR
        score: 3500
      - name: Maximum 1080p
        score: 3500


  - trash_ids:
      - 2f22d89048b01681dde8afe203bf2e95 # DTS X
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 3200
      - name: Maximum 4K/SDR
        score: 3200
      - name: Maximum 1080p
        score: 3200
      - name: Optimized 4k
        score: 1900
      - name: Optimized 1080p
        score: 1900

  - trash_ids:
      - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 3000
      - name: Maximum 4K/SDR
        score: 3000
      - name: Maximum 1080p
        score: 3000

  - trash_ids:
      - 185f1dd7264c4562b9022d963ac37424 # DD+
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 1300
      - name: Maximum 4K/SDR
        score: 1300
      - name: Maximum 1080p
        score: 1300
      - name: Optimized 4k
        score: 1800
      - name: Optimized 1080p
        score: 2300

  - trash_ids:
      - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 1200
      - name: Maximum 4K/SDR
        score: 1200
      - name: Maximum 1080p
        score: 1200

  - trash_ids:
      - 1c1a4c5e823891c75bc50380a6866f73 # DTS
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 1250
      - name: Maximum 4K/SDR
        score: 1250
      - name: Maximum 1080p
        score: 1250

  - trash_ids:
      - c2998bd0d90ed5621d8df281e839436e # DD
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 750
      - name: Maximum 4K/SDR
        score: 750
      - name: Maximum 1080p
        score: 750
      - name: Optimized 4k
        score: 700
      - name: Optimized 1080p
        score: 2500

  # Release Groups Tiers
  - trash_ids:
      - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
      - 9f98181fe5a3fbeb0cc29340da2a468a # Remux Tier 02
      - 8baaf0b3142bf4d94c42a724f034e27a # Remux Tier 03
    assign_scores_to:
      - name: Maximum 4K/HDR
      - name: Maximum 4K/SDR
      - name: Maximum 1080p

  - trash_ids:
      - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
      - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
      - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
    assign_scores_to:
      - name: Maximum 4K/HDR
      - name: Maximum 4K/SDR
      - name: Maximum 1080p
      - name: Optimized 4k
      - name: Optimized 1080p


  - trash_ids:
      - 4d74ac4c4db0b64bff6ce0cffef99bf0 # UHD Bluray Tier 01
      - a58f517a70193f8e578056642178419d # UHD Bluray Tier 02
      - e71939fae578037e7aed3ee219bbe7c1 # UHD Bluray Tier 03
    assign_scores_to:
      - name: Maximum 4K/HDR
      - name: Maximum 4K/SDR
      - name: Optimized 4k
    

  - trash_ids:
      - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
      - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
      - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
    assign_scores_to:
      - name: Maximum 1080p

  - trash_ids:
      - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
      - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
      - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
    assign_scores_to:
      - name: Optimized 1080p
        score: -10000


  # Repack / Proper
  - trash_ids:
      - e7718d7a3ce595f289bfee26adc178f5 # Repack / Proper
      - ae43b294509409a6a13919dedd4764c4 # Repack2 / Proper2
    assign_scores_to:
      - name: Maximum 4K/HDR
      - name: Maximum 4K/SDR
      - name: Maximum 1080p
      - name: Optimized 4k
      - name: Optimized 1080p


  # Unwanted
  - trash_ids:
      - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
      - cae4ca30163749b891686f95532519bd # AV1
      - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
      - ed38b889b31be83fda192888e2286d83 # BR-DISK
      - 0a3f082873eb454bde444150b70253cc # Extras
      - e6886871085226c3da1830830146846c # Generated Dynamic HDR
      - d6e9318c875905d6cfb5bee961afcea9 # Language: Not Original
      - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
    assign_scores_to:
      - name: Maximum 4K/HDR
      - name: Maximum 4K/SDR
      - name: Maximum 1080p
      - name: Optimized 4k
      - name: Optimized 1080p

  - trash_ids:
      - a5d148168c4506b55cf53984107c396e # 10bit
    assign_scores_to:
      - name: Optimized 1080p
        score: -10000


  - trash_ids:
      - 90a6f9a284dff5103f6346090e6280c8 # LQ
      - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
    assign_scores_to:
      - name: Maximum 4K/HDR
      - name: Maximum 4K/SDR
      - name: Maximum 1080p

  # Unwanted Maximum
  - trash_ids:
      - b2be17d608fc88818940cd1833b0b24c # 720p
      - 820b09bb9acbfde9c35c71e0e565dad8 # 1080p
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: -10000
      - name: Maximum 4K/SDR
        score: -10000
      - name: Optimized 4k
        score: -10000

  - trash_ids:
     # - a3e19f8f627608af0211acd02bf89735 # DV SDR
      - 9c38ebb7384dada637be8899efa68e6f # SDR
     # - 9364dd386c9b4a1100dde8264690add7 # HLG
     # - 08d6d8834ad9ec87b1dc7ec8148e7a1f # PQ
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: -10000
      - name: Optimized 4k
        score: -10000

  # Prefer HDR10+ Boost

  - trash_ids:
       - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 200
      - name: Optimized 4k
        score: 200
      - name: Optimized 1080p
        score: -10000

  # Prefer DV Boost
  - trash_ids:
       - b337d6812e06c200ec9a2d3cfa9d20a7 # DV Boost
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 360
      - name: Optimized 4k
        score: 360
      - name: Optimized 1080p
        score: -10000

  #  HDR Catch All
  - trash_ids:
      - 493b6d1dbec3c3364c59d7607f7e3405 # HDR Catch All
      # - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
      # - b974a6cd08c1066250f1f177d7aa1225 # HDR10+          
      # - e61e28db95d22bedcadf030b8f156d96 # HDR
      # - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 1500
      - name: Optimized 4k
        score: 1500
      - name: Optimized 1080p
        score: -10000

  # Censorship
  - trash_ids:
      - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
    assign_scores_to:
      - name: Maximum 4K/HDR
        score: 10
      - name: Maximum 4K/SDR
        score: 10
      - name: Maximum 1080p
        score: 10
      - name: Optimized 4k
        score: 10
      - name: Optimized 1080p
        score: 10